### ISSUE TITLE
[Web/css] image selection option as flag `--no-drag`

### ISSUE THREAD

**Issue by softmarshmallow** [gridaco/designto-code#91]
![image](https://user-images.githubusercontent.com/16307013/144384461-8988dccf-6074-42f7-8a6c-8764279f21ca.png)

Add flag support to make image non draggable by user.

```txt
Layer: non-dragable-image --no-drag
```

will generate

```css
.image-no-drag{
    user-select: none;
    -webkit-user-drag: none;
}
```
